services:
  - type: web
    name: movie-recommendation-backend
    env: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true

    pythonVersion: "3.12.12"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-db
          property: connectionString

      - key: SECRET_KEY
        sync: false

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "movie-recommendation-backend.onrender.com"

      - key: TMDB_API_KEY
        sync: false

      - key: TMDB_CACHE_TTL
        value: "3600"

databases:
  - name: movie-db
    plan: free

